const fs = require('fs');
const p = 'C:/Users/DUAN/Desktop/iosmovie/iosmovie/Sources/DDYSSource.swift';

const lines = [];
lines.push('import Foundation');
lines.push('');
lines.push('final class DDYSSource: MovieSourceProtocol {');
lines.push('    let sourceName = "低端影视"');
lines.push('    let baseURL = "https://ddys.io"');
lines.push('');
lines.push('    private let session: URLSession');
lines.push('');
lines.push('    init() {');
lines.push('        let config = URLSessionConfiguration.default');
lines.push('        config.httpAdditionalHeaders = [');
lines.push('            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",');
lines.push('            "Accept": "application/json, text/plain, */*"');
lines.push('        ]');
lines.push('        self.session = URLSession(configuration: config)');
lines.push('    }');
lines.push('');
lines.push('    func fetchHomeMovies() async throws -> [MovieItem] {');
lines.push('        guard let url = URL(string: baseURL + "/api/hot-movies") else { throw URLError(.badURL) }');
lines.push('        let (data, _) = try await session.data(from: url)');
lines.push('        let resp = try JSONDecoder().decode(HotMoviesResponse.self, from: data)');
lines.push('        return resp.data.map { item in');
lines.push('            MovieItem(id: String(item.id ?? 0), title: item.title, type: item.type ?? "", year: String(item.year ?? 0), rating: item.rating ?? "", detailURL: item.url ?? "")');
lines.push('        }');
lines.push('    }');
lines.push('');
lines.push('    func searchMovies(keyword: String) async throws -> [MovieItem] {');
lines.push('        guard let encoded = keyword.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),');
lines.push('              let url = URL(string: baseURL + "/api/search-suggest?q=" + encoded) else { throw URLError(.badURL) }');
lines.push('        let (data, _) = try await session.data(from: url)');
lines.push('        let resp = try JSONDecoder().decode(SearchResponse.self, from: data)');
lines.push('        return resp.data.map { item in');
lines.push('            MovieItem(id: item.slug ?? "", title: item.title, type: item.type ?? "", year: String(item.year ?? 0), rating: item.rating ?? "", detailURL: item.url ?? "")');
lines.push('        }');
lines.push('    }');
lines.push('');
lines.push('    func fetchMovieDetail(path: String) async throws -> MovieDetail {');
lines.push('        let fullPath = path.hasPrefix("http") ? path : baseURL + path');
lines.push('        guard let url = URL(string: fullPath) else { throw URLError(.badURL) }');
lines.push('        var request = URLRequest(url: url)');
lines.push('        request.setValue("text/html,application/xhtml+xml", forHTTPHeaderField: "Accept")');
lines.push('        let (data, _) = try await session.data(for: request)');
lines.push('        guard let html = String(data: data, encoding: .utf8) else { throw URLError(.cannotDecodeContentData) }');
lines.push('');
lines.push('        let movieId = extractMovieId(from: html) ?? ""');
lines.push('        let title = extractTitle(from: html) ?? ""');
lines.push('        let sources = extractPlaySources(from: html)');
lines.push('        return MovieDetail(movieId: movieId, title: title, sources: sources)');
lines.push('    }');
lines.push('');
lines.push('    private func extractMovieId(from html: String) -> String? {');
lines.push('        guard let range = html.range(of: "const movieId = ") else { return nil }');
lines.push('        var digits = ""');
lines.push('        var index = range.upperBound');
lines.push('        while index < html.endIndex, digits.count < 10 {');
lines.push('            let char = html[index]');
lines.push('            if char.isNumber { digits.append(char) }');
lines.push('            else if !digits.isEmpty { break }');
lines.push('            index = html.index(after: index)');
lines.push('        }');
lines.push('        return digits.isEmpty ? nil : digits');
lines.push('    }');
lines.push('');
lines.push('    private func extractTitle(from html: String) -> String? {');
lines.push('        guard let range = html.range(of: "<title>") else { return nil }');
lines.push('        let start = range.upperBound');
lines.push('        guard let endRange = html.range(of: "</title>", range: start..<html.endIndex) else { return nil }');
lines.push('        return String(html[start..<endRange.lowerBound])');
lines.push('    }');
lines.push('');
lines.push('    private func extractPlaySources(from html: String) -> [PlaySource] {');
lines.push('        var sources: [PlaySource] = []');
lines.push('        let pattern = #"switchSource\(\s*(\d+)\s*,\s*\'([^\']+)\'\s*,\s*\'([^\']+)\'"#');
lines.push('        if let regex = try? NSRegularExpression(pattern: pattern) {');
lines.push('            let nsRange = NSRange(html.startIndex..<html.endIndex, in: html)');
lines.push('            let matches = regex.matches(in: html, range: nsRange)');
lines.push('            for match in matches {');
lines.push('                guard let idRange = Range(match.range(at: 1), in: html),');
lines.push('                      let urlRange = Range(match.range(at: 2), in: html),');
lines.push('                      let formatRange = Range(match.range(at: 3), in: html) else { continue }');
lines.push('                let id = String(html[idRange])');
lines.push('                let rawURL = String(html[urlRange])');
lines.push('                let format = String(html[formatRange])');
lines.push('                let cleanURL = rawURL.replacingOccurrences(of: "\\/", with: "/")');
lines.push('                sources.append(contentsOf: parseSource(id: id, rawURL: cleanURL, format: format))');
lines.push('            }');
lines.push('        }');
lines.push('');
lines.push('        if sources.isEmpty {');
lines.push('            if let firstSourceURL = extractFirstSourceURL(from: html) {');
lines.push('                sources.append(contentsOf: parseSource(id: "1", rawURL: firstSourceURL, format: "m3u8"))');
lines.push('            }');
lines.push('        }');
lines.push('');
lines.push('        return sources');
lines.push('    }');
lines.push('');
lines.push('    private func parseSource(id: String, rawURL: String, format: String) -> [PlaySource] {');
lines.push('        if rawURL.contains("#") && rawURL.contains("$") {');
lines.push('            let parts = rawURL.components(separatedBy: "#")');
lines.push('            var episodes: [PlaySource] = []');
lines.push('            for (index, part) in parts.enumerated() {');
lines.push('                let segments = part.components(separatedBy: "$")');
lines.push('                if segments.count >= 2 {');
lines.push('                    let name = segments[0]');
lines.push('                    let url = segments[1]');
lines.push('                    episodes.append(PlaySource(id: "\(id)-ep\(index + 1)", name: name, url: url, format: format))');
lines.push('                }');
lines.push('            }');
lines.push('            let container = PlaySource(id: id, name: "源 \(id)", url: "", format: format, episodes: episodes)');
lines.push('            return [container]');
lines.push('        } else {');
lines.push('            return [PlaySource(id: id, name: "源 \(id)", url: rawURL, format: format)]');
lines.push('        }');
lines.push('    }');
lines.push('');
lines.push('    private func extractFirstSourceURL(from html: String) -> String? {');
lines.push('        guard let range = html.range(of: "firstSource") else { return nil }');
lines.push('        let snippet = String(html[range.lowerBound...].prefix(1500))');
lines.push('        let pattern = #"url\s*[:=]\s*\\"([^\\"]+)\\""#');
lines.push('        guard let regex = try? NSRegularExpression(pattern: pattern),');
lines.push('              let match = regex.firstMatch(in: snippet, range: NSRange(snippet.startIndex..<snippet.endIndex, in: snippet)),');
lines.push('              let urlRange = Range(match.range(at: 1), in: snippet) else { return nil }');
lines.push('        let rawURL = String(snippet[urlRange])');
lines.push('        return rawURL.replacingOccurrences(of: "\\/", with: "/")');
lines.push('    }');
lines.push('}');
lines.push('');
lines.push('private struct HotMoviesResponse: Codable { let data: [HotMovieItem] }');
lines.push('private struct HotMovieItem: Codable {');
lines.push('    let id: Int?');
lines.push('    let title: String');
lines.push('    let type: String?');
lines.push('    let year: Int?');
lines.push('    let rating: String?');
lines.push('    let url: String?');
lines.push('}');
lines.push('');
lines.push('private struct SearchResponse: Codable { let data: [SearchItem] }');
lines.push('private struct SearchItem: Codable {');
lines.push('    let title: String');
lines.push('    let slug: String?');
lines.push('    let type: String?');
lines.push('    let year: Int?');
lines.push('    let rating: String?');
lines.push('    let url: String?');
lines.push('}');
lines.push('');

const content = lines.join('\n');
fs.writeFileSync(p, content, 'utf8');
console.log('written, total lines:', lines.length);
